### PR TITLE
Minor fixes in README.md

### PR DESCRIPTION
**Pull request by omacchioni**
one typo which blocks compilation
some other minor cosmetic changes

### CODE REVIEW

**Comment by toni-moreno** [comment]
Hi @omacchioni thank you very much for your contribution. 
Before doing the merge I would like to know  why have you changed the typescript version on the package.json and what typescript version are you working right now after the change?

**Comment by omacchioni** [comment]
Hi @toni-moreno 

Sorry, this was not intended to be committed - I'm not fully familiar with npm and all those tools, so I was simply trying to fix the README at this stage :/

It's probably a side-effect of me running `npm install typescript@'>=2.1.0 <2.4.0'` because  of the following message when running `npm build --prod`:

```
@angular/compiler-cli@4.3.6 requires typescript@'>=2.1.0 <2.4.0' but 2.6.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.1.0 <2.4.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".
```

**Comment by toni-moreno** [comment]
It's ok and a very good job @omacchioni , but I would like to test next days before merge on the main branch. ( I'm not sure my node version could have any issue with the chosen typescript version , and I need a stable building platform in order to build next releases binaries )  :)

**Comment by toni-moreno** [comment]
Hi @omacchioni I've tested the new typescript version 2.6.2 chosen instead  and All seems work fine  , but the warning is shown again. 

````
@angular/compiler-cli@4.3.6 requires typescript@'>=2.1.0 <2.4.0' but 2.6.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.
 
Please run the following command to install a compatible version of TypeScript.
 
    npm install typescript@'>=2.1.0 <2.4.0'
 
 To disable this warning run "ng set warnings.typescriptMismatch=false".

````
With the package.json changes you has not fixed the warning , in this context I prefer don't change it and  I would like to ask you for a new PR without this related changes please!

Thank you very much , and I will wait for your new PR!

**Comment by omacchioni** [comment]
Doing a new pull request...

**Pull request closed without merging**
