### PR TITLE
xorm update:

### PR DESCRIPTION
**Pull request by dcarbone**
- updates xorm from github/go-xorm/* to xorm.io/*
- fixes default value on `SnmpDeviceCfg.Active` to be compatible with mariadb, mysql, and pgsql

### CODE REVIEW

**Comment by toni-moreno** [comment]
Hello @dcarbone , thank you this PR. 

The new feature will be welcomed , but there is a failing check , because it has not been well designed. It seems like is not working when a PR is done from other user repo ( obviously without the needed credentials for docker hub login  ).  Could you please  remove on your branch these lines from the action ( https://github.com/toni-moreno/snmpcollector/blob/master/.github/workflows/pr-docker-image-test.yml#L25-L30)  to test the docker image generation again ?

**Comment by dcarbone** [comment]
@toni-moreno: anything else I can add to this PR to get it accepted?

**Comment by toni-moreno** [comment]
> @toni-moreno: anything else I can add to this PR to get it accepted?

Only was waiting for your reply in the previous question.

@dcarbone , thank you in advance for your work. Prior to merge I would like to know what DB are you working on and what other db engines have you tested after this change has been done.

**Comment by dcarbone** [comment]
@toni-moreno: sure, so I can personally verify that it works with mariadb, and the documentation for [postgres 9.1+](https://www.postgresql.org/docs/9.1/datatype-boolean.html) and [mysql 5.6+](https://dev.mysql.com/doc/refman/5.6/en/boolean-literals.html) indicate that `TRUE` is valid constant for this field type.

**Review by toni-moreno — APPROVED** [review]

**Pull request merged**
